---
title: "More Prompts"
---

In this section we will create a template string to ask the LLM the capital of
a place. Then we will ask it for some facts about the capital. Finally we will
provide some formatting guidelines about the response.

## Template For Asking For a Capital

Create a template string with a template variable `place` for asking the LLM to
give you the capital of `place`. Then evaluate the template variable using
`"Texas"` and `"France"`. Print out the two prompts that you get by doing that.

Fill in the appropriate sections of the code below where you see the word CODE.

- Define a template that asks for the capital of {place}
- Evaluate the template using `place="Texas"`

```{python}
#| eval: false
# Define template here
CODE

# Evaluate the template with place="Texas"
prompt=template.format(CODE)
print(prompt)
```
```{python}
# Solution:
# Define template here
template = "Can you tell me the capital of {place}?"

# Evaluate the template with place="Texas"
prompt=template.format(place="Texas")
print(prompt)
```

- Evaluate the template using `place="France"`

```{python}
#| eval: false
# Evaluate the template with place="France"
prompt=template.format(CODE)
print(prompt)
```
```{python}
# Solution:
# Evaluate the template with place="France"
prompt=template.format(place="France")
print(prompt)
```

## Adding a Variable Called `num`

- Add another template variable called `num` and ask the LLM to provide you
  with `num` facts about the capital that you specified with `place`.
- Evaluate the tempate using `place="Texas"` and `num=3`

```{python}
#| eval: false
# Define template here
CODE

# Evaluate the template for "Texas" and 3 facts
prompt=template.format(CODE)
print(prompt)
```
```{python}
# Solution:
# Define template here
template = """Can you tell me the capital of {place} and give me {num} simple
facts about it?"""

# Evaluate the template for "Texas" and 3 facts
prompt=template.format(place="Texas", num=3)
print(prompt)
```

## Ask To Format the Response

Add a template variable called `format` so you can pass in the desired format
for the facts that are given.

- Add a template variable called `format` and ask the model to format it
  according to that
- Evaluate the template using `place="Texas`, `num=3` and `format="upper case"`

```{python}
#| eval: false
# Define template here
CODE

# Evaluate the template for "Texas" and 3 facts, and "upper case"
prompt=template.format(CODE)
print(prompt)
```
```{python}
# Solution:
# Define template here
template ="""Can you tell me the capital of {place} and give me {num} simple
facts about it?.
Format the facts using {format}"""

# Evaluate the template for "Texas" and 3 facts, and "upper case"
prompt=template.format(place="Texas", num=3, format="upper case")
print(prompt)
```

## Asking About Several Capitals

Let's see how this looks if we ask for the capital of several places.

- Create a list called `myPlaces` with the following places on it: California,
  Missouri, Florida.  Use strings for the items on the list.
- Create 3 prompts asking for the capital using a for loop


```{python}
#| eval: false
# Define template here
template = "Can you tell me the capital of {place}?"

# Create the list of places.
myPlaces = CODE

# Loop through the myPlaces and print each prompt template.
for place in myPlaces:
  prompt = template.format(CODE)
  print(prompt)
  print("----")
```
```{python}
# Solution:
# Define template here
template = "Can you tell me the capital of {place}?"

myPlaces = ["California", "Missouri", "Florida"]

for place in myPlaces:
  prompt = template.format(place=place)
  print(prompt)
  print("----")
```
