---
title: "More Variables in Python"
execute:
    eval: false
---

__Problem__: Lets start by storing a number in a variable. Store 4 in the variable `x`

```{python}
CODE
```
```{python}
# __SOLUTION__
x=4
```

__Problem__: Print out the variable `x`:

```{python}
CODE
```
```{python}
# __SOLUTION__
print(x)
```

__Problem__: Set `y` equal to `5*x`

```{python}
CODE
```
```{python}
# __SOLUTION__
y=5*x
```
Now y will have a value after we do this. What is the current value of y? Since the current value of `x` is 4, the value of y should be $5(4)=20$.

__Problem__: Now print out the value of `y`

```{python}
CODE
```
```{python}
# __SOLUTION__
print(y)
```

Variables can be changed as a program proceeds.

__Problem__: Change the value of x to be 7:

```{python}
CODE
```
```{python}
# __SOLUTION__
x=7
```

__Problem__: One thing you might wonder is that if you change the value of x at some point, does that affect the value of y we defined earlier using x? Let's check:
```{python}
CODE
```
```{python}
# __SOLUTION__
print(y)
```

No. It doesn't. This y still has the same value it had before which is $5(4) = 20$ since at the time we assigned y the x was equal to 4.
If we want y to update, we would have to assign it again to give it a new value. Go ahead and do that.  

__Problem__: Define `y` to be `5*x`

```{python}
CODE
```
```{python}
# __SOLUTION__
y=5*x
```

__Problem__: Now print out the new version of y using `print`:

```{python}
CODE
```
```{python}
# __SOLUTION__
print(y)
```
It has the value $5(7) = 35$ now since currently the x is assigned to be 7.

__Problem__: Next go ahead and set a variable `z` equal to 1.2 and `w` equal to 7 and then print them both out in this block of code

```{python}
CODE
```
```{python}
# __SOLUTION__
z=1.2
w=7
print(z)
print(w)
```

__Problem__: Now we change (assign) `z` to be `3*w-5` and print out the new `z`
```{python}
CODE
```
```{python}
# __SOLUTION__
z=3*w-5
print(z)
```
Since `w` was 7 above, the new value of `z` is $3(7)-5 = 16$

