---
title: "More LLM Chain"
---

```{python}
#| eval: false

```
```{python}
# Solution:

```

{{< include _llm_togetherai.qmd >}}

## Suggest a Company Name and Upper It

### Step 1: Suggest a Funny Company Name

Lets start by creating a variable for our product request.

```{python}
car = "sports cars"
```

- Write a prompt template that has the LLM suggest one funny name for a company
  that makes a certain product.
- Make `product` a template variable and use `{product}` in your template

```{python}
#| eval: false
company_template ="""

CODE

"""
```
```{python}
# Solution:
company_template ="""
Create a funny name for a company that makes:

{product}
"""
```

- Pass `car` to the format function as the template variable `{product}`
- Pass the `company_prompt` to `get_completion` to get the LLM's response
- Print the `company_response`

```{python}
#| eval: false
company_prompt = company_template.format(product=CODE)
company_response = get_completion(CODE)
print(CODE)
```
```{python}
# Solution:
company_prompt = company_template.format(product=car)
company_response = get_completion(company_prompt)
print(company_response)
```

### Step 2: Upper Case the Name and Product

Upper case the company

- Write a prompt template using both `{product}` and `{company}` as template
  variables, asking the LLM to upper case the company name and the product
```{python}
#| eval: false
uppercase_template ="""

CODE

"""
```
```{python}
# Solution:
uppercase_template ="""

Please upper case the company name and the product:

Product:
{product}

Company:
{company}
"""
```

- Pass the `company_response` as the `company` variable and `car` as the
  `product` variable
- Pass the `uppercase_prompt` to `get_completion` to get the LLM's response
  Print the `uppercase_response`
```{python}
#| eval: false
uppercase_prompt = uppercase_template.format(company=CODE,
                                             product=CODE)
uppercase_response = get_completion(CODE)
print(CODE)
```
```{python}
# Solution:
uppercase_prompt = uppercase_template.format(company=company_response,
                                             product=car)
uppercase_response = get_completion(uppercase_prompt)
print(uppercase_response)
```

### Final Report

```{python}
report_template = """
## Final Report

### Product
{product}

### Company Name
{company}

### Upper Cased Company and Product
{uppercase}
"""

report = report_template.format(product = car,
                         company = company_response,
                         uppercase = uppercase_response)
print(report)
```
