---
title: "Simple Order Bot"
---

```{python}
#| eval: true 
model_name="openai/gpt-4o-mini"
```

{{< include _llm_openrouter.qmd >}}

## Here we are building a simple bot to take pizza orders:

Create an order bot, which is an automated service to collect orders for a
pizza restaurant. Come up with a set of intructions for the `system_prompt`
below.

The following is the menu:

Pizzas  

- pepperoni pizza  \$12.95, \$10.00, \$7.00
- cheese pizza   \$10.95, \$9.25, \$6.50
- eggplant pizza   \$11.95, \$9.75, \$6.75

Sides

- fries \$4.50, \$3.50
- greek salad \$7.25

Toppings

- extra cheese \$2.00,
- mushrooms \$1.50
- sausage \$3.00
- canadian bacon \$3.50
- peppers \$1.00

Drinks

- coke \$3.00, \$2.00, \$1.00
- sprite \$3.00, \$2.00, \$1.00
- bottled water \$5.00

Here are some things to implement. Try to implement and test each of these.

## Requirements for the OrderBot

- Greet the customer and introduce yourself as "The Order Technician"
- Be able to display the entire menu or just a category depending on the users
requests 
- If the customer orders a item, ask them what size they want.
- Confirm each item with the name of the item, the size and the price
- Once you have any items on the customer's order, show the current order and
   total at the bottom of each response from you. Give the order details in a
   table 
- Once the user is ready ask the user for their name and their phone number.
- Ask them if they will pickup or want delivery. If they want delivery get an
   address.

Apply the following multi-tiered discount system based on the order total, customer type, and day of the week:

- If order total < $20, no discount
- Else if order total < $50, 5% discount
- Else if order total < $100, 10% discount
- Else 15% discount
- If the customer is a senior citizen, add an additional 5% discount
- If it's Tuesday, add an extra 2% "Taco Tuesday" discount

Make sure to add all the discounts before discounting. For example if the order
is 23.95, then there is a 5% discount. If it is "Taco Tuesday" add another 2%
to the discount so that is becomes a 7% discount.

Be sure to tell your chatbot to double check the arithmetic when it does it.

```{python}
#| eval: false
system_prompt = """ You are a helpful assistant.

<<< REPLACE WITH YOUR OWN DETAILS BUT LEAVE MENU BELOW>>>

Below is the menu between the <menu> </menu> tags. It is in markdown. Please
preserve the backslashes in front of the dollar signs when showing money
amounts.

<menu>
Pizzas  

- pepperoni pizza  \$12.95, \$10.00, \$7.00
- cheese pizza   \$10.95, \$9.25, \$6.50
- eggplant pizza   \$11.95, \$9.75, \$6.75

Sides

- fries \$4.50, \$3.50
- greek salad \$7.25

Toppings

- extra cheese \$2.00,
- mushrooms \$1.50
- sausage \$3.00
- canadian bacon \$3.50
- peppers \$1.00

Drinks

- coke \$3.00, \$2.00, \$1.00
- sprite \$3.00, \$2.00, \$1.00
- bottled water \$5.00
</menu>
"""

initial_message = "Welcome ..."
run_chatbot(system_prompt, initial_message)
```

```{python}
#| eval: false
print_messages()
```
